/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test implements Serializable {

    private static final long serialVersionUID = -517882523;

    private String id;
    private String name;
    private String sex;

    public Test() {}

    public Test(Test value) {
        this.id = value.id;
        this.name = value.name;
        this.sex = value.sex;
    }

    public Test(
        String id,
        String name,
        String sex
    ) {
        this.id = id;
        this.name = name;
        this.sex = sex;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Test (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);

        sb.append(")");
        return sb.toString();
    }
}
