/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1343220269;

    private String id;
    private String name;
    private String phone;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.phone = value.phone;
    }

    public User(
        String id,
        String name,
        String phone
    ) {
        this.id = id;
        this.name = name;
        this.phone = phone;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
