/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.data;


import com.example.jooq.data.tables.Test;
import com.example.jooq.data.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.test</code>.
     */
    public static final Test TEST = com.example.jooq.data.tables.Test.TEST;

    /**
     * The table <code>jooq.user</code>.
     */
    public static final User USER = com.example.jooq.data.tables.User.USER;
}
